apply plugin:'wrapper'
apply plugin:'groovy'
apply plugin:'signing'
apply plugin:'maven'

wrapper {
    gradleVersion = '4.5'
}

buildDir = project.file('target')

group = 'ch.raffael.gradlePlugins.preshadow'
version = '1.0-SNAPSHOT'

archivesBaseName = 'gradle-preshadow-plugin'

sourceCompatibility='1.7'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    compile localGroovy()
    compile gradleApi()

    compile group:'com.github.johnrengelman', name:'shadow', version:'1.2.3'
}

task sourcesJar(type:Jar) {
    classifier = 'sources'

    from sourceSets.main.allSource
}

task javadocJar(type:Jar) {
    classifier = 'javadoc'

    from groovydoc
}

artifacts {
    archives sourcesJar, javadocJar
}
